import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
import './globals.scss';
import dynamic from 'next/dynamic';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const PageView = dynamic(() => import('./page'));

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageView />
      </body>
      <Toaster />
    </html>
  );
}
